# Generated by Django 5.0.2 on 2024-03-23 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdeaBlog',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fikr_blog.basemodel')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'Idea Blog',
                'verbose_name_plural': 'Idea Blogs',
            },
            bases=('fikr_blog.basemodel',),
        ),
    ]
